#!/usr/bin/python

import json
import sys

def dump(data):
    if type(data) is dict:
        print json.dumps(data, indent=2)
    else:
        print data

if len(sys.argv) < 2:
    print "No file specified. Usage: %s <file> [path]" % sys.argv[0]
    sys.exit(1)

file = sys.argv[1]
path = None

if len(sys.argv) > 2:
    path = sys.argv[2]

with open(file, 'r') as json_file:
    data = json.load(json_file)

if path is None:
    dump(data)
else:
    parts = path.split('|')
    here=data
    for part in parts:
      if len(part) < 1:
        continue
      here = here[part]

    dump(here)

