#!/bin/bash
#
# Copyright (C) 2015 John Casey (jdcasey@commonjava.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -x

DIR=$(dirname $(dirname $(realpath $0)))
source $DIR/ENV

$BASE/scripts/autodeploy-url.py --service=$SERVICE_NAME \
                                --versionfile=$VERSION_FILE \
                                --image=$IMAGE_NAME \
                                --name=$CONTAINER_NAME \
                                $EXTRA_UPGRADE_PARAMS \
                                --url="$URL" \
                                $BASE/scripts/init-indy -q  --url={url}
